server:
  port: 8082
spring:
  application:
    name: CamundaEngine
    discovery:
      enabled: true

  cloud:
    config:
      enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:adel}
    password: ${DB_PASS:passer123}
    url: jdbc:postgresql://${DB_HOST:10.42.1.204}:${DB_PORT:5432}/${DB_NAME:camunda}
    hibernate.ddl-auto: validate
  jpa:
    hibernate:
      ddl-auto: update

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  config:
    import:
      optional:
        configserver: ${CONFIG_SERVER:http://localhost:8888 }


camunda:
  bpm.admin-user:
    id: ${CAMUNDA_USERNAME:demo}
    password: ${CAMUNDA_PASSWORD:demo}
# Logger configuration

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://registry:8761/eureka/}

camunda.bpm.client:
  base-url: ${BASE_URL_CAMUNDA:http://localhost:8080/engine-rest }# the URL pointing to the Camunda Platform Runtime REST API
  lock-duration: 10000 # defines how many milliseconds the External Tasks are locked until they can be fetched again
logging.level.org.camunda.bpm.client: DEBUG # increase the log level of the application


